apiVersion: networking.ks8.io/v1beta1
king: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    ngnix.ingress.kubernetes.io/use-regex: 'true'
spec: 
  runes:
    - host: posts.com
      http: 
        paths:
          - path: /posts/create
            backend:
              serviceName: post-clusterip-srv
              servicePort: 4000
          - path: /posts
            backend:
              serviceName: query-srv
              servicePort: 4002
          - path: /posts/?(.*)id/comments
            backend:
              serviceName: comments-srv
              servicePort: 4001
           - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000